// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OtakuQuest.Server.Data;

#nullable disable

namespace OtakuQuest.Server.Migrations
{
    [DbContext(typeof(OtakuQuestDbContext))]
    [Migration("20260401091740_AddItemsSystem")]
    partial class AddItemsSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OtakuQuest.Server.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DefBonus")
                        .HasColumnType("int");

                    b.Property<float>("DefMultiplier")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HpBonus")
                        .HasColumnType("int");

                    b.Property<float>("HpMultiplier")
                        .HasColumnType("real");

                    b.Property<string>("ImageAsset")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IntBonus")
                        .HasColumnType("int");

                    b.Property<float>("IntMultiplier")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("StrBonus")
                        .HasColumnType("int");

                    b.Property<float>("StrMultiplier")
                        .HasColumnType("real");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("OtakuQuest.Server.Models.TodoTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DifficultyRank")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("OtakuQuest.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AvatarItemId")
                        .HasColumnType("int");

                    b.Property<int?>("BackgroundItemId")
                        .HasColumnType("int");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<int>("CurrentHP")
                        .HasColumnType("int");

                    b.Property<int>("DEF")
                        .HasColumnType("int");

                    b.Property<int?>("EquippedAvatarId")
                        .HasColumnType("int");

                    b.Property<int?>("EquippedBackgroundId")
                        .HasColumnType("int");

                    b.Property<int?>("EquippedWeaponId")
                        .HasColumnType("int");

                    b.Property<int>("INT")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MaxHP")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("STR")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("XP")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquippedAvatarId");

                    b.HasIndex("EquippedBackgroundId");

                    b.HasIndex("EquippedWeaponId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OtakuQuest.Server.Models.UserItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("UserItems");
                });

            modelBuilder.Entity("OtakuQuest.Server.Models.TodoTask", b =>
                {
                    b.HasOne("OtakuQuest.Server.Models.User", "User")
                        .WithMany("Tasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OtakuQuest.Server.Models.User", b =>
                {
                    b.HasOne("OtakuQuest.Server.Models.Item", "EquippedAvatar")
                        .WithMany()
                        .HasForeignKey("EquippedAvatarId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("OtakuQuest.Server.Models.Item", "EquippedBackground")
                        .WithMany()
                        .HasForeignKey("EquippedBackgroundId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("OtakuQuest.Server.Models.Item", "EquippedWeapon")
                        .WithMany()
                        .HasForeignKey("EquippedWeaponId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("EquippedAvatar");

                    b.Navigation("EquippedBackground");

                    b.Navigation("EquippedWeapon");
                });

            modelBuilder.Entity("OtakuQuest.Server.Models.UserItem", b =>
                {
                    b.HasOne("OtakuQuest.Server.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OtakuQuest.Server.Models.User", "User")
                        .WithMany("Inventory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OtakuQuest.Server.Models.User", b =>
                {
                    b.Navigation("Inventory");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
